import data from '~/data/mods.json'

/** One published mod: a family's bundle or one of its parts. Generated by `yarn mods` from the mods' gradle.properties. */
export type ModDetails = {
  id: string
  dir: string
  name: string
  shortName: string
  slug: string
  description: string
  /** Slug in the CurseForge project URL; empty until the project exists. */
  curseforgeSlug: string
  /** Slug or project id in the Modrinth URL; empty until the project exists. */
  modrinthSlug: string
  logo: string
  route: string
}

/** A repo of related mods. Most ship a bundle that includes every part; Assorted Util does not. */
export type Family = {
  key: string
  id: string
  name: string
  route: string
  github: string
  description: string
  /** The bundle's logo, or one made for a family that has no bundle. */
  logo: string
  bundle: ModDetails | null
  parts: ModDetails[]
}

export const Constants = {
  CurseUrl: 'https://www.curseforge.com/minecraft/mc-mods/',
  ModrinthUrl: 'https://modrinth.com/mod/'
}

export const FAMILIES: Family[] = data.families

/** Assorted Lib, which every family needs. It has its own page but is not a family. */
export const LIB: ModDetails & { github: string } = data.lib

/** Lib's own pages, listed under it in the sidebar. */
export const LIB_PAGES = [
  { name: 'Instruction Manual', route: '/lib/instruction-manual' }
]

export function getFamily(key: string): Family {
  const family = FAMILIES.find(f => f.key === key)
  if (!family) throw new Error(`no family ${key} in mods.json; run yarn mods`)
  return family
}

export function getPart(familyKey: string, slug: string): ModDetails {
  const part = getFamily(familyKey).parts.find(p => p.slug === slug)
  if (!part) throw new Error(`no mod ${slug} in ${familyKey}; run yarn mods`)
  return part
}

export function curseforgeUrl(mod: ModDetails | null): string | null {
  return mod?.curseforgeSlug ? Constants.CurseUrl + mod.curseforgeSlug : null
}

export function modrinthUrl(mod: ModDetails | null): string | null {
  return mod?.modrinthSlug ? Constants.ModrinthUrl + mod.modrinthSlug : null
}
